# This is a basic workflow to help you get started with Actions

name: nubit

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute-script:
    runs-on: ubuntu-latest  # 定义运行环境为最新的 Ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install curl -y  # 确保 curl 已安装

    - name: Execute nubit.sh Script
      run: curl -sL1 https://nubit.sh | bash  # 执行你的命令
